// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx9FI4NyfkiaWXh4sxjhxrJq9rXVjhYt4',
    appId: '1:62628924150:web:cefc9c4606ac0724837ad7',
    messagingSenderId: '62628924150',
    projectId: 'hisab-app-63959',
    authDomain: 'hisab-app-63959.firebaseapp.com',
    storageBucket: 'hisab-app-63959.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5EUNdAMSD_ttmP9c745CgzfPhw8rN7fQ',
    appId: '1:62628924150:android:1f7b0978f8f36cb2837ad7',
    messagingSenderId: '62628924150',
    projectId: 'hisab-app-63959',
    storageBucket: 'hisab-app-63959.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_3I_0HIrZM-hqetIyx84d-8bd6zOOFQU',
    appId: '1:62628924150:ios:b568214b4e381ccf837ad7',
    messagingSenderId: '62628924150',
    projectId: 'hisab-app-63959',
    storageBucket: 'hisab-app-63959.firebasestorage.app',
    iosBundleId: 'com.example.expenseApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_3I_0HIrZM-hqetIyx84d-8bd6zOOFQU',
    appId: '1:62628924150:ios:b568214b4e381ccf837ad7',
    messagingSenderId: '62628924150',
    projectId: 'hisab-app-63959',
    storageBucket: 'hisab-app-63959.firebasestorage.app',
    iosBundleId: 'com.example.expenseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx9FI4NyfkiaWXh4sxjhxrJq9rXVjhYt4',
    appId: '1:62628924150:web:0c5049f6ea632848837ad7',
    messagingSenderId: '62628924150',
    projectId: 'hisab-app-63959',
    authDomain: 'hisab-app-63959.firebaseapp.com',
    storageBucket: 'hisab-app-63959.firebasestorage.app',
  );
}
